import Head from "next/head";
import Image from "next/image";
import PageLayoutSidebar from "../src/components/common/PagelayoutSidebar";
import SideBar from "../src/components/common/Sidebar";
import StartPageMainComponent from "../src/components/startpage/StartPageMainComponent";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <PageLayoutSidebar>
      <Head>
        <title>Verktøyregister</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <StartPageMainComponent />
    </PageLayoutSidebar>
  );
}
